# Python DA Assignment 1: Data Analysis using NumPy and Pandas

## 1. NumPy Array Operations

### 1.1 Import NumPy

In [1]:
import numpy as np

### 1.2 Create a 1D NumPy Array

Create `temperatures_w1` for Week 1 using the temperatures provided in the question.

In [2]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

### 1.3 Inspect Shape, Data Type, and Number of Elements

In [3]:
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7

### 1.4 Convert Celsius to Fahrenheit

Formula: **Fahrenheit = (Celsius × 9/5) + 32**

In [5]:
temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:")
print(temperatures_f)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

### 1.5 Find Maximum, Minimum, and Mean Temperature

In [6]:
maximum_temperature = np.max(temperatures_w1)
minimum_temperature = np.min(temperatures_w1)
mean_temperature = np.mean(temperatures_w1)

print("Maximum temperature:", maximum_temperature)
print("Minimum temperature:", minimum_temperature)
print("Mean temperature:", round(mean_temperature, 2))

Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.54

### 1.6 Array Slicing and Indexing

Extract the first three days, weekend temperatures, and middle three days.

In [7]:
first_three_days = temperatures_w1[:3]
weekend = temperatures_w1[-2:]
middle_three_days = temperatures_w1[2:5]

print("First three days:", first_three_days)
print("Weekend:", weekend)
print("Middle three days:", middle_three_days)

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

## 2. Create and Analyze a 2D NumPy Array

Each row represents the temperatures for one week.

In [8]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

### 2.1 Inspect Shape, Data Type, and Total Number of Elements

In [10]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14

### 2.2 Extract Each Week and the Weekend Temperatures

In [11]:
week1 = temperatures[0]
week2 = temperatures[1]
week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]

print("Week 1:", week1)
print("Week 2:", week2)
print("Week 1 weekend:", week1_weekend)
print("Week 2 weekend:", week2_weekend)

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

# 3. Pandas Series

## 3.1 Import Pandas and Create the Series

In [12]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

## 3.2 Indexing and Slicing

In [15]:
print("Mark of 1st rank student:", marks.iloc[0])

print("Top 3 ranks using loc:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

print("Mark of 3rd rank student using iloc:", marks.iloc[2])

print("Ranks with marks greater than 90:")
print(marks[marks > 90])

Mark of 1st rank student: 95
Top 3 ranks using loc:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
Mark of 3rd rank student using iloc: 89
Ranks with marks greater than 90:
Rank1    95
Rank2    92
dtype: int64

## 3.3 Manipulating the Series

Modify Rank1, remove Rank5, and calculate CGPA by dividing each mark by 10.

In [16]:
marks.loc['Rank1'] = 100
marks = marks.drop('Rank5')
cgpa = marks / 10

print("Updated marks:")
print(marks)

print("CGPA:")
print(cgpa)

Updated marks:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

# 4. Pandas DataFrame

## 4.1 Create the Transactions DataFrame

In [17]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

## 4.2 Data Exploration

### Display the DataFrame

In [28]:
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### Display the Head and Tail

In [19]:
print("First 5 rows:")
display(transactions.head())

print("Last 5 rows:")
display(transactions.tail())

First 5 rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### Shape, Column Names, and Data Types

In [20]:
print("Shape:", transactions.shape)
print("Column names:", list(transactions.columns))
print("Data types:")
print(transactions.dtypes)

Shape: (10, 4)
Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
Data types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

### Display ProductCategory and Amount

In [21]:
transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

### Retrieve the Last 3 Columns Using iloc

In [23]:
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

### Filter North Region and Amount Greater Than 200

In [24]:
filtered_transactions = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

filtered_transactions

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

### Value Counts for ProductCategory

In [25]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

### Unique Values in Region

In [26]:
transactions['Region'].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

### Mean Amount by Region

In [27]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

## 4.3 Manipulating the DataFrame

### Modify TransactionID 102

In [29]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

### Add a Discount Column

The discount is calculated as 10% of the Amount.

In [30]:
transactions['Discount'] = transactions['Amount'] * 0.10
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

### Remove TransactionID 109

In [31]:
transactions = transactions[transactions['TransactionID'] != 109]
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

### Delete the Discount Column

In [32]:
transactions = transactions.drop(columns='Discount')
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400